HairSalon/Models/Client.cs
namespace HairSalon.Models
{
    public class Client
    {
        public int ClientId { get; set; }
        public int StylistId { get; set; }
        public virtual Stylist Stylist { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PhoneNumber { get; set; }
    }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
    public class HairSalonContext : DbContext
    {
        public virtual DbSet<Stylist> Stylists { get; set; } 
        public DbSet<Client> Clients { get; set; }

        public HairSalonContext(DbContextOptions options) : base(options) { }
    }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
    public class Stylist
    {
        public Stylist()
        {
            this.Clients = new HashSet<Client>();
        }
        public virtual ICollection<Client> Clients { get; set; }
        public int StylistId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string HireDate { get; set; }
        public int HourlyWage { get; set; }
    }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
    public class ClientsController : Controller
    {
        private readonly HairSalonContext _db;

        public ClientsController(HairSalonContext db)
        {
            _db = db;
        }

        public ActionResult Create(int id)
        {
            ViewBag.StylistId = id;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Client client)
        {
            _db.Clients.Add(client);
            _db.SaveChanges();
            return RedirectToAction("Details", "Stylists", new { id = client.StylistId });
        }

        public ActionResult Details(int id)
        {
            Client client = _db.Clients.Include(c => c.Stylist).FirstOrDefault(s => s.ClientId == id);
            return View(client);
        }

        public ActionResult Delete(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(c => c.ClientId == id);
            return View(thisClient);
        }

         [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisClient = _db.Clients.FirstOrDefault(c => c.ClientId == id);
            _db.Clients.Remove(thisClient);
            _db.SaveChanges();
            return RedirectToAction("Details", "Stylists", new { id = thisClient.StylistId });
        }
    }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Controllers
{
    public class StylistsController : Controller
    {
        private readonly HairSalonContext _db;

        public StylistsController(HairSalonContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Stylist> model = _db.Stylists.ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Stylist stylist)
        {
            _db.Stylists.Add(stylist);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Stylist stylist = _db.Stylists.Include(s => s.Clients).FirstOrDefault(s => s.StylistId == id);
            return View(stylist);
        }

        public ActionResult Delete(int id)
        {
            var thisStylist = _db.Stylists.FirstOrDefault(s => s.StylistId == id);
            return View(thisStylist);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisStylist = _db.Stylists.FirstOrDefault(s => s.StylistId == id);
            _db.Stylists.Remove(thisStylist);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var thisStylist = _db.Stylists.FirstOrDefault(s => s.StylistId == id);
            return View(thisStylist);
        }

        [HttpPost]
        public ActionResult Edit(Stylist stylist)
        {
            _db.Entry(stylist).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client
<h1>Add a Client</h1>
<hr>
@using (Html.BeginForm())
{
    <input type="hidden" name="StylistId" value=@ViewBag.StylistId />
    @Html.Label("Name", "Name: ") @Html.TextBoxFor(model => model.Name, new { @class="form-control", required="required"})

    @Html.Label("Description", "Phone number: ") @Html.TextBoxFor(model => model.PhoneNumber, new { @class="form-control"})

    @Html.Label("Description", "Other Info: ") @Html.TextBoxFor(model => model.Description, new { @class="form-control"})

    <input type="submit" value="Add Client" class="btn btn-default"/>
}

<button class="btn btn-default">@Html.ActionLink("Back to Clients List", "Details", "Stylists", new { id = ViewBag.StylistId })</button>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h1>Delete Client</h1>
<hr>
<h3><strong>Are you sure you want to delete @Model.Name?</strong></h3>
@using (Html.BeginForm())
{
    <input type="submit" value="Yes, Delete This Client" class="btn btn-default" />
}

<button class="btn btn-default">@Html.ActionLink("Back To ???", "???", new { id = @Model.StylistId })</button>

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client
@using HairSalon.Models

<h1>Client: @Model.Name</h1>
<hr>
@if (!String.IsNullOrEmpty(Model.PhoneNumber))
{
  <p><strong>Phone Number: </strong>@Model.PhoneNumber</p>
}
@if (!String.IsNullOrEmpty(Model.Description))
{
  <p><strong>More Info About @Model.Name: </strong>@Model.Description</p>
}

<button class="btn btn-default">@Html.ActionLink("Delete This Client", "Delete", new { id = Model.ClientId })</button>
<button class="btn btn-default">@Html.ActionLink("Back to Clients List", "Details", "Stylists", new { id = Model.StylistId })</button>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1 class="splash">Eau Claire's Salon</h1>
<img src="~/img/chairs.jpg">
<button class="btn btn-default">@Html.ActionLink("Stylists", "Index", "Stylists")</button>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Eau Claire's Salon</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Sacramento&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
        @RenderBody()
    </div>
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
<h1>Add a Stylist</h1>
<hr>
@using (Html.BeginForm())
{
    @Html.Label("Name", "Name: ") @Html.TextBoxFor(model => model.Name, new { @class="form-control", required="required"})

    @Html.Label("HireDate", "Date Hired: ") @Html.TextBoxFor(model => model.HireDate, new { @class="form-control"})

    @Html.Label("HourlyWage", "Hourly wage: $") @Html.TextBoxFor(model => model.HourlyWage, new { @class="form-control",  type="number"})

    @Html.Label("Description", "Other Info: ") @Html.TextBoxFor(model => model.Description, new { @class="form-control"})

    <input type="submit" value="Add Stylist" class="btn btn-default"/>
}

<button class="btn btn-default">@Html.ActionLink("Back to Stylists List", "Index")</button>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h1>Delete Stylist</h1>
<hr>
<h3><strong>Are you sure you want to delete @Model.Name?</strong></h3>
@using (Html.BeginForm())
{
    <input type="submit" value="Yes, Delete This Stylist" class="btn btn-default" />
}

<button class="btn btn-default">@Html.ActionLink("Back To Stylist", "Details", new { id = @Model.StylistId })</button>

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
@using HairSalon.Models

<h1>Stylist: @Model.Name</h1>
<hr>
@if (!String.IsNullOrEmpty(Model.HireDate))
{
  <p><strong>Eau Claire's Stylist Since: </strong>@Model.HireDate</p>
}
@if (Model.HourlyWage != 0)
{
  <p><strong>Hourly Wage: </strong>$@Model.HourlyWage</p>
}
@if (!String.IsNullOrEmpty(Model.Description))
{
  <p><strong>More Info About @Model.Name: </strong>@Model.Description</p>
}
<hr>
<h4>@Model.Name's Clients:</h4>
@if (Model.Clients.Count == 0)
{
  <p>No clients have been added yet.</p>
}
@foreach(Client client in @Model.Clients)
{
  <li>@Html.ActionLink($"{client.Name}", "Details", "Clients", new { id = client.ClientId })</li>
}

<button class="btn btn-default">@Html.ActionLink("Add a Client", "Create", "Clients", new { id = Model.StylistId })</button>
<button class="btn btn-default">@Html.ActionLink("Edit This Stylist", "Edit", new { id = Model.StylistId })</button>
<button class="btn btn-default">@Html.ActionLink("Delete This Stylist", "Delete", "Stylists", new { id = Model.StylistId })</button>
<button class="btn btn-default">@Html.ActionLink("Back to Stylists List", "Index")</button>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h1>Edit Stylist</h1>
<hr>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.StylistId)

    @Html.Label("Name", "Name: ") @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })

    @Html.Label("HireDate", "Date Hired: ") @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control" } })

    @Html.Label("HourlyWage", "Hourly wage: $") @Html.EditorFor(model => model.HourlyWage, new { htmlAttributes = new { @class = "form-control", type="number" } })

    @Html.Label("Description", "Other Info: ") @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })

    <input type="submit" value="Save" class="btn btn-default"/>
}

<button class="btn btn-default">@Html.ActionLink("Back To Stylist", "Details", new { id = @Model.StylistId })</button>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models
@model List<HairSalon.Models.Stylist>

<h1>Eau Claire's Stylists</h1>
<hr>
@if (@Model.Count == 0)
{
  <h3>No stylists have been added yet.</h3>
} 

<ul>
@foreach (Stylist stylist in Model)
{
  <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
}
</ul>

<button class="btn btn-default">@Html.ActionLink("Add A Stylist", "Create")</button>
<button class="btn btn-default">@Html.ActionLink("Home", "Index", "Home")</button>